#!/usr/bin/env bash
# =============================================================================
# SmartHR360 platform bootstrap — one command from zero to seeded stack.
#
#   ./bootstrap.sh                 keys + .env + build + up + seed (small+full)
#   ./bootstrap.sh --seed small    only the quick demo story
#   ./bootstrap.sh --seed full     only the big dataset
#   ./bootstrap.sh --seed none     infrastructure only, no data
#   ./bootstrap.sh --no-build      docker compose up without --build
#   ./bootstrap.sh --reset         WIPE all data (down -v) then full re-run
#   ./bootstrap.sh --down          stop the stack (data volumes kept)
#
# Idempotent: existing keys and .env are NEVER overwritten; seeds are
# check-before-create. Secrets are generated dynamically by
# scripts/gen_secret.sh — no hardcoded values anywhere.
# =============================================================================
set -euo pipefail

cd "$(dirname "$0")"

SEED_MODE="both"
BUILD_FLAG="--build"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --seed)      SEED_MODE="${2:?--seed needs small|full|both|none}"; shift 2 ;;
    --no-build)  BUILD_FLAG=""; shift ;;
    --reset)     echo "Wiping all containers AND data volumes…";
                 docker compose down -v; shift ;;
    --down)      docker compose down; exit 0 ;;
    -h|--help)   grep '^#   ' "$0" | sed 's/^#   //'; exit 0 ;;
    *) echo "unknown option: $1 (try --help)"; exit 1 ;;
  esac
done

bold()  { printf '\033[1m%s\033[0m\n' "$*"; }
ok()    { printf '  \033[32m✔\033[0m %s\n' "$*"; }
warn()  { printf '  \033[33m⚠\033[0m %s\n' "$*"; }
fail()  { printf '  \033[31m✘\033[0m %s\n' "$*"; exit 1; }

# -----------------------------------------------------------------------------
bold "[0/5] Prerequisites"
# -----------------------------------------------------------------------------
command -v docker  >/dev/null 2>&1 || fail "docker is not installed / not in PATH"
docker compose version >/dev/null 2>&1 || fail "docker compose v2 is required"
docker info >/dev/null 2>&1 || fail "docker daemon is not running — start Docker Desktop first"
command -v python3 >/dev/null 2>&1 || fail "python3 is required for the seed scripts"
ok "docker, compose, python3"

# git submodules (services/) must be present to build
if [ ! -f services/smarthr360-auth/manage.py ]; then
  warn "service submodules look empty — running: git submodule update --init"
  git submodule update --init --recursive
fi
ok "service submodules present"

# -----------------------------------------------------------------------------
bold "[1/5] RSA keys for JWT signing (one-time)"
# -----------------------------------------------------------------------------
if [ -f keys/jwt_private.pem ] && [ -f keys/jwt_public.pem ]; then
  ok "keys/ already present — keeping existing keys"
else
  ./scripts/generate_rsa_keys.sh
  ok "generated keys/jwt_private.pem + keys/jwt_public.pem"
fi

# -----------------------------------------------------------------------------
bold "[2/5] Secrets (.env) — dynamically generated (one-time)"
# -----------------------------------------------------------------------------
if [ -f .env ]; then
  ok ".env already present — keeping existing secrets"
else
  chmod +x scripts/gen_secret.sh
  # each value comes straight from the generator script's stdout
  cat > .env <<EOF
# Generated by bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) — do not commit.
POSTGRES_PASSWORD=$(./scripts/gen_secret.sh 32)
AUTH_SECRET_KEY=$(./scripts/gen_secret.sh)
CORE_HR_SECRET_KEY=$(./scripts/gen_secret.sh)
CAREER_SIM_SECRET_KEY=$(./scripts/gen_secret.sh)
WORKLOAD_SECRET_KEY=$(./scripts/gen_secret.sh)
POLICY_GEN_SECRET_KEY=$(./scripts/gen_secret.sh)
RETENTION_SECRET_KEY=$(./scripts/gen_secret.sh)
FUTURE_SKILLS_SECRET_KEY=$(./scripts/gen_secret.sh)
EOF
  chmod 600 .env
  ok ".env written with 8 fresh random secrets (chmod 600)"
fi

# -----------------------------------------------------------------------------
bold "[3/5] docker compose up ${BUILD_FLAG:-'(no build)'}"
# -----------------------------------------------------------------------------
# shellcheck disable=SC2086
docker compose up -d $BUILD_FLAG
ok "stack starting in the background"

# -----------------------------------------------------------------------------
bold "[4/5] Waiting for services to be healthy"
# -----------------------------------------------------------------------------
SERVICES_PORTS="auth:8000 core-hr:8001 career-sim:8003 workload:8005 policy-gen:8006 retention:8007"
OPTIONAL_PORTS="future-skills:8004"
DEADLINE=$(( $(date +%s) + 300 ))   # 5 minutes

wait_one() { # name port required(0/1)
  local name="$1" port="$2" required="$3"
  while true; do
    if curl -sf -o /dev/null "http://localhost:${port}/healthz/"; then
      ok "$name (:$port)"
      return 0
    fi
    if [ "$(date +%s)" -ge "$DEADLINE" ]; then
      if [ "$required" = "1" ]; then
        echo; docker compose logs --tail 30 "$name" || true
        fail "$name did not become healthy — logs above"
      else
        warn "$name (:$port) not up — optional, continuing"
        return 0
      fi
    fi
    sleep 3
  done
}

for entry in $SERVICES_PORTS; do wait_one "${entry%%:*}" "${entry##*:}" 1; done
for entry in $OPTIONAL_PORTS;  do wait_one "${entry%%:*}" "${entry##*:}" 0; done

# frontend (no /healthz — probe the login page)
if curl -sf -o /dev/null "http://localhost:3100/login"; then
  ok "frontend (:3100)"
else
  warn "frontend (:3100) not answering yet — it may still be building"
fi

# -----------------------------------------------------------------------------
bold "[5/5] Seeding data (mode: $SEED_MODE)"
# -----------------------------------------------------------------------------
if [ "$SEED_MODE" != "none" ]; then
  # the seed scripts need the 'requests' package
  if ! python3 -c "import requests" >/dev/null 2>&1; then
    warn "python 'requests' missing — installing for the current user"
    python3 -m pip install --user --quiet requests \
      || python3 -m pip install --user --quiet --break-system-packages requests
  fi
  case "$SEED_MODE" in
    small) python3 scripts/seed_demo.py ;;
    full)  python3 scripts/seed_demo_full.py ;;
    both)  python3 scripts/seed_demo.py && python3 scripts/seed_demo_full.py ;;
    *)     fail "--seed must be small|full|both|none" ;;
  esac
fi

echo
bold "== SmartHR360 is ready =="
echo "  Frontend   http://localhost:3100"
echo "  Grafana    http://localhost:3000   Prometheus http://localhost:9090"
echo "  API docs   http://localhost:8001/docs/ (core-hr — same pattern per service)"
if [ "$SEED_MODE" != "none" ]; then
  echo "  Accounts   admin/hr/manager/employee @demo.smarthr360.dev"
  echo "             password: Demo#2026!hr360 (see scripts/platform_client.py)"
fi
echo "  Stop with  ./bootstrap.sh --down"
