apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smarthr360
resources:
- namespace.yaml
- postgres.yaml
- auth.yaml
- core-hr.yaml
- career-sim.yaml
- future-skills.yaml
- ingress.yaml
- workload.yaml
- policy-gen.yaml
- retention.yaml
- workload-cronjob.yaml
images:
- name: ghcr.io/nawfalrazouk7/smarthr360-auth
  newTag: main
- name: ghcr.io/nawfalrazouk7/smarthr360-core-hr
  newTag: main
- name: ghcr.io/nawfalrazouk7/smarthr360-career-sim
  newTag: main
- name: ghcr.io/nawfalrazouk7/smarthr360_m3_future_skills
  newTag: main
- name: ghcr.io/nawfalrazouk7/smarthr360-workload
  newTag: main
- name: ghcr.io/nawfalrazouk7/smarthr360-policy-gen
  newTag: main
- name: ghcr.io/nawfalrazouk7/smarthr360-retention
  newTag: main
